### ISSUE TITLE
[Request] Support for Novation Launchpad S?

### ISSUE THREAD

**Issue by ChasarooniZ** [CDeenen/MaterialServer#11]
If possible would be nice

**Comment by CDeenen** [comment]
In theory it should be possible to add support for the Launchpad S. However, there are some obstacles:
First, it uses a different protocol than the newer Launchpads. So it'd be quite a bit of work to adapt things to it.
Second, I don't own one, which means that I wouldn't be able to test it myself, making debugging very difficult.

If you have programming experience you could try it yourself, but if you decide to go that route I suggest you wait a bit until I've updated [Material Companion](https://github.com/materialfoundry/materialcompanion) to support Material Keys.
