### ISSUE TITLE
MacOS arm64 won't open.

### ISSUE THREAD

**Issue by omidmash** [CDeenen/MaterialServer#8]
The app, downloaded and unzipped, gives the error "the application cannot be launched".

`The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600000e9dbc0 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}`

shows when I try to launch from Terminal. 

After giving permission to the binary via chmod, launching the app gives "material server quit unexpectedly", and launching binary via terminal gives:
```
Last login: Mon Mar 13 14:37:50 on ttys001
/Applications/materialserver.app/Contents/MacOS/materialserver ; exit;          
yser.@user-Mac-mini ~ % /Applications/materialserver.app/Contents/MacOS/materialserver ; exit;
dyld[11551]: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: <4C4C442B-5555-3144-A180-4E6DD1FDB80F> /Applications/materialserver.app/Contents/MacOS/materialserver
  Reason: tried: '/Applications/materialserver.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' (), '/Applications/materialserver.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' (), '/System/Volumes/Preboot/Cryptexes/OS@rpath/Electron Framework.framework/Electron Framework' (no such file), '/Applications/materialserver.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' (), '/Applications/materialserver.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' (), '/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/System/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file, not in dyld cache)
zsh: abort      /Applications/materialserver.app/Contents/MacOS/materialserver

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by CDeenen** [comment]
In issue #7 they mention clearing extended attributes, which has worked for some.
In the terminal, execute `xattr -cr /Applications/materialserver.app`
This hasn't worked for everyone, in which case you can try [building the app from the source](https://github.com/CDeenen/MaterialServer/wiki/Running-and-Building-From-the-Source).

**Comment by omidmash** [comment]
The solution from issue #7 did not work. Building the app works, but only half way. I can build the app from scratch, but there are midi dependancies that are not working. After changing the package file to latest version of easymidi and removing midi completely, it runs but I can't build it due to dmgmaker errors.

**Comment by CDeenen** [comment]
Could you try running `npm update` and build again?

**Comment by omidmash** [comment]
That worked! Thank you.
